feat : create page UI prototype
DEV-TINO/Mango-Diary-JY pull request #1
Opened 2024-01-13 10:22 UTC by jzongyun

## Docs

- [figma design prototype](https://www.figma.com/file/0ByGSnJpm6DdAwqOrPSSeR/Untitled?type=design&mode=design&t=YzW6JA1YS0Tq0IU0-1)

## Changes

- before :
- after :
- images

## Review Points

#### Problem

#### Solution

## Test Checklist

- [ ] check 1
- [ ] check 2

2024-01-14 07:29 UTC, kim-song-jun requested changes
👍 
Plz add Footer.

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/public/images/logo2.png
change a meaningful name

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/public/images/mood1.jpg
change a meaningful name

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/public/images/mood2.jpg
change a meaningful name

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/public/images/mood2c.jpg
change a meaningful name

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/public/images/mood3.jpg
change a meaningful name

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +
delete line

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +            <option v-for="(month, index) in 12" :key="index + 1" :value="index + 1">{{ monthNames[index] }}</option>
key must be immutable value

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +
delete empty line

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +              {{ day == null ? "-" : day }}
make display function like this
```
showDay(day) {
  return day == null ? '-' : day
}
```

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +              <div class="day-container" :class="{ today: isToday(day) }" @click="writeDiary()"></div>
check css parameter

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +      selectedYear: new Date().getFullYear(),
make function like this
```
getToday() {
  this.selectedYear: new Date().getFullYear()
   ...
}

mounted() {
   this.getToday()
}
```

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +      dayNames: ['Sun', 'Mon', 'Tues', 'Wed', 'Thur', 'Fri', 'Sat'],
how about using vuex?

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +    monthNames() {
see above

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +      let calendar = [];
using `const`

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +      for (let i = 0; i < 6; i++) {
make const value for calendar `row` and `col`

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +      this.$router.push('/writing');
path must be handle in variable.

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +footer{
do not use tag selector. make some css class

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/SplashPage.vue
> +    <h4 @click="redirectToCalendar" class="start">Touch to Start</h4>
change `redirectToCalendar` to `redirectToCalendar()`

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/SplashPage.vue
> +      this.$router.push('/calendar');
see above

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +        <select id="yearSelect" v-model="selectedYear" @change="updateStatistics">
see above

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +      <img src="/images/logo2.png" class="logo">
see above

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +          <option v-for="(month, index) in 12" :key="index + 1" :value="index + 1">{{ monthNames[index] }}</option>
see above

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +      <router-link to="/calendar">캘린더</router-link>
check path

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +.mostSelectedEmoji{
change name
`.most-select-emoji`

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +h4 {
do not use tag selector

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/WritePage.vue
> +        <img class="selctedImage" v-if="!selectedImage" src="/images/photo.png">
change image to `<div>` box or `input` box

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/WritePage.vue
> +      moodEmojis: [
using vuex

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/components/WritePage.vue
> +h3 {
see above

2024-01-14 07:29 UTC, kim-song-jun commented on MangoDiary/src/main.js
> +import router from './router'
add `.js`

2024-01-22 04:25 UTC, jzongyun commented
Done

2024-01-25 10:35 UTC, kim-song-jun reviewed
🥇

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/public/images/logo2.png
does it changed?

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +              <div class="day-container" :class="{ today: isToday(day) }" @click="writeDiary()"></div>
Is it solved?

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +      let calendar = [];
Is it solved?

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/SplashPage.vue
> +      this.$router.push(this.$store.state.calendar);
delete `;`

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/CalendarPage.vue
> +            week.push(dayCount++);
delete all `;`

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +      return Array.from({ length: 10 }, (_, index) => currentYear - index);
delete `;`

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/StatisticsPage.vue
> +  data() {
delete `data()`

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/WritePage.vue
> +        @change="handleImageUpload"
add `()` end of function.

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/components/WritePage.vue
> +      this.$router.push(this.$store.state.calendar);
remove `;`

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/router.js
> +    {path: "/",
add space after `{`

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/store.js
> +            moodEmojis: ['grey/angry','grey/depressed','grey/pleased','grey/happy','grey/sad'],
how about make prefix for `grey` or `color`?

2024-01-25 10:35 UTC, kim-song-jun commented on MangoDiary/src/store.js
> +            originalEmojis: ['grey/angry','grey/depressed','grey/pleased','grey/happy','grey/sad'],
Why that 2 variable is same? Where it used? Why it needed?

2024-01-28 08:31 UTC, kim-song-jun approved these changes

2024-01-28 08:35 UTC, kim-song-jun reviewed
👍

2024-01-28 08:35 UTC, merged